# Воспользуемся официальным образом для запуска python.
FROM python:3.10

# Обновим компоненты в контейнере.
RUN apt-get update -y

# Копируем все файлы в контейнер.
COPY . .

# Запускаем установку зависимостей.
RUN pip install -r requirements.txt

# Устанавливаем сертификат для подключения к ресурсам в Яндекс Облаке.
RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

# Переходим в директорию src
WORKDIR /src

# Говорим, что запускать будем python.
ENTRYPOINT ["python"]

# А именно, файл app.py в директории src.
CMD ["app.py"]